name: 'Build Micro-app'
description: 'Workflow for building an microapp'
inputs:
  path:
    description: 'The path to the microapp'
    required: true
    default: '.'
runs:
  using: "composite"
  steps:
    - name: Install
      shell: bash
      working-directory: ${{ inputs.path }}
      run: |
        npm install -g pnpm
        pnpm install --filter .

#    - name: Test
#      shell: bash
#      working-directory: ${{ inputs.path }}
#      run: |
#        npm run test-all

    - name: build
      shell: bash
      working-directory: ${{ inputs.path }}
      run: |
        pnpm run build