name: Node.js CI - Root

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy staging
        if: github.event.release.prerelease == 'true'
        run: |
          echo "Deploying..."

      - name: Deploy production
        if: github.event.release.prerelease == 'false'
        run: |
          echo "Deploying..."
