name: Node.js CI - Root

on:
  push:
    branches:
      - '**'
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        microapps: ["WEBHOOK_ROOT", "WEBHOOK_SYLLABUS", "WEBHOOK_CAMPUS", "WEBHOOK_FEEDS"]
    env:
      url: ${{ secrets[matrix.microapps] }}
    steps:
      - name: Deploy staging
        run:
          curl -X POST -d {} "${{ env.url }}" -H "Content-Type:application/json"

      - name: Deploy production
        if: github.event.release.prerelease == false
        run: |
          echo "Deploying..."
