# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    paths:
      - 'campus/**'
    branches:
      - '**'

defaults:
  run:
    working-directory: ./your_working_dir

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/microapp
        with:
          path: campus