name: Node.js CI - Syllabus

on:
  push:
    branches: [ '**' ]
    paths:
      - 'syllabus/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL_M }}
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
      REACT_APP_BLOG_S3_BASE_URL: https://wasedatime-feeds.s3-ap-northeast-1.amazonaws.com
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - uses: ./.github/actions/microapp
        with:
          path: 'syllabus'